// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package yara_x

import (
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *easyjson.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm(in *jlexer.Lexer, out *warningList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(warningList, 0, 0)
			} else {
				*out = warningList{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 Warning
			easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm1(in, &v1)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm(out *jwriter.Writer, in warningList) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm1(out, v3)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v warningList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v warningList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *warningList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *warningList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm(l, v)
}
func easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm1(in *jlexer.Lexer, out *Warning) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = WarningType(in.String())
			}
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = string(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "line":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Line = int(in.Int())
			}
		case "column":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Column = int(in.Int())
			}
		case "labels":
			if in.IsNull() {
				in.Skip()
				out.Labels = nil
			} else {
				in.Delim('[')
				if out.Labels == nil {
					if !in.IsDelim(']') {
						out.Labels = make([]Label, 0, 0)
					} else {
						out.Labels = []Label{}
					}
				} else {
					out.Labels = (out.Labels)[:0]
				}
				for !in.IsDelim(']') {
					var v4 Label
					easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm2(in, &v4)
					out.Labels = append(out.Labels, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "footers":
			if in.IsNull() {
				in.Skip()
				out.Footers = nil
			} else {
				in.Delim('[')
				if out.Footers == nil {
					if !in.IsDelim(']') {
						out.Footers = make([]Footer, 0, 2)
					} else {
						out.Footers = []Footer{}
					}
				} else {
					out.Footers = (out.Footers)[:0]
				}
				for !in.IsDelim(']') {
					var v5 Footer
					easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm3(in, &v5)
					out.Footers = append(out.Footers, v5)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm1(out *jwriter.Writer, in Warning) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix)
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"line\":"
		out.RawString(prefix)
		out.Int(int(in.Line))
	}
	{
		const prefix string = ",\"column\":"
		out.RawString(prefix)
		out.Int(int(in.Column))
	}
	if len(in.Labels) != 0 {
		const prefix string = ",\"labels\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v6, v7 := range in.Labels {
				if v6 > 0 {
					out.RawByte(',')
				}
				easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm2(out, v7)
			}
			out.RawByte(']')
		}
	}
	if len(in.Footers) != 0 {
		const prefix string = ",\"footers\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v8, v9 := range in.Footers {
				if v8 > 0 {
					out.RawByte(',')
				}
				easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm3(out, v9)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix)
		out.String(string(in.Text))
	}
	out.RawByte('}')
}
func easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm3(in *jlexer.Lexer, out *Footer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "level":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Level = string(in.String())
			}
		case "text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm3(out *jwriter.Writer, in Footer) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"level\":"
		out.RawString(prefix[1:])
		out.String(string(in.Level))
	}
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix)
		out.String(string(in.Text))
	}
	out.RawByte('}')
}
func easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm2(in *jlexer.Lexer, out *Label) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "level":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Level = string(in.String())
			}
		case "code_origin":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CodeOrigin = string(in.String())
			}
		case "line":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Line = int64(in.Int64())
			}
		case "column":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Column = int64(in.Int64())
			}
		case "span":
			easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm4(in, &out.Span)
		case "text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm2(out *jwriter.Writer, in Label) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"level\":"
		out.RawString(prefix[1:])
		out.String(string(in.Level))
	}
	{
		const prefix string = ",\"code_origin\":"
		out.RawString(prefix)
		out.String(string(in.CodeOrigin))
	}
	{
		const prefix string = ",\"line\":"
		out.RawString(prefix)
		out.Int64(int64(in.Line))
	}
	{
		const prefix string = ",\"column\":"
		out.RawString(prefix)
		out.Int64(int64(in.Column))
	}
	{
		const prefix string = ",\"span\":"
		out.RawString(prefix)
		easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm4(out, in.Span)
	}
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix)
		out.String(string(in.Text))
	}
	out.RawByte('}')
}
func easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm4(in *jlexer.Lexer, out *Span) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "start":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Start = int(in.Int())
			}
		case "end":
			if in.IsNull() {
				in.Skip()
			} else {
				out.End = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm4(out *jwriter.Writer, in Span) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"start\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Start))
	}
	{
		const prefix string = ",\"end\":"
		out.RawString(prefix)
		out.Int(int(in.End))
	}
	out.RawByte('}')
}
func easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm5(in *jlexer.Lexer, out *ruleJSONList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(ruleJSONList, 0, 0)
			} else {
				*out = ruleJSONList{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v10 ruleJSON
			easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm6(in, &v10)
			*out = append(*out, v10)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm5(out *jwriter.Writer, in ruleJSONList) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v11, v12 := range in {
			if v11 > 0 {
				out.RawByte(',')
			}
			easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm6(out, v12)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v ruleJSONList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ruleJSONList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ruleJSONList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ruleJSONList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm5(l, v)
}
func easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm6(in *jlexer.Lexer, out *ruleJSON) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "n":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Namespace = string(in.String())
			}
		case "i":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Identifier = string(in.String())
			}
		case "t":
			if in.IsNull() {
				in.Skip()
				out.Tags = nil
			} else {
				in.Delim('[')
				if out.Tags == nil {
					if !in.IsDelim(']') {
						out.Tags = make([]string, 0, 4)
					} else {
						out.Tags = []string{}
					}
				} else {
					out.Tags = (out.Tags)[:0]
				}
				for !in.IsDelim(']') {
					var v13 string
					if in.IsNull() {
						in.Skip()
					} else {
						v13 = string(in.String())
					}
					out.Tags = append(out.Tags, v13)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "p":
			if in.IsNull() {
				in.Skip()
				out.Patterns = nil
			} else {
				in.Delim('[')
				if out.Patterns == nil {
					if !in.IsDelim(']') {
						out.Patterns = make([]patternJSON, 0, 1)
					} else {
						out.Patterns = []patternJSON{}
					}
				} else {
					out.Patterns = (out.Patterns)[:0]
				}
				for !in.IsDelim(']') {
					var v14 patternJSON
					easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm7(in, &v14)
					out.Patterns = append(out.Patterns, v14)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "m":
			if in.IsNull() {
				in.Skip()
				out.Metadata = nil
			} else {
				in.Delim('[')
				if out.Metadata == nil {
					if !in.IsDelim(']') {
						out.Metadata = make([]metadataJSON, 0, 1)
					} else {
						out.Metadata = []metadataJSON{}
					}
				} else {
					out.Metadata = (out.Metadata)[:0]
				}
				for !in.IsDelim(']') {
					var v15 metadataJSON
					easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm8(in, &v15)
					out.Metadata = append(out.Metadata, v15)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm6(out *jwriter.Writer, in ruleJSON) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"n\":"
		out.RawString(prefix[1:])
		out.String(string(in.Namespace))
	}
	{
		const prefix string = ",\"i\":"
		out.RawString(prefix)
		out.String(string(in.Identifier))
	}
	{
		const prefix string = ",\"t\":"
		out.RawString(prefix)
		if in.Tags == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v16, v17 := range in.Tags {
				if v16 > 0 {
					out.RawByte(',')
				}
				out.String(string(v17))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"p\":"
		out.RawString(prefix)
		if in.Patterns == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v18, v19 := range in.Patterns {
				if v18 > 0 {
					out.RawByte(',')
				}
				easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm7(out, v19)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"m\":"
		out.RawString(prefix)
		if in.Metadata == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v20, v21 := range in.Metadata {
				if v20 > 0 {
					out.RawByte(',')
				}
				easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm8(out, v21)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}
func easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm8(in *jlexer.Lexer, out *metadataJSON) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "i":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Identifier = string(in.String())
			}
		case "v":
			easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm9(in, &out.Value)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm8(out *jwriter.Writer, in metadataJSON) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"i\":"
		out.RawString(prefix[1:])
		out.String(string(in.Identifier))
	}
	{
		const prefix string = ",\"v\":"
		out.RawString(prefix)
		easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm9(out, in.Value)
	}
	out.RawByte('}')
}
func easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm9(in *jlexer.Lexer, out *metadataValueJSON) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "k":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Kind = string(in.String())
			}
		case "v":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Value).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm9(out *jwriter.Writer, in metadataValueJSON) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"k\":"
		out.RawString(prefix[1:])
		out.String(string(in.Kind))
	}
	{
		const prefix string = ",\"v\":"
		out.RawString(prefix)
		(in.Value).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}
func easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm7(in *jlexer.Lexer, out *patternJSON) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "i":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Identifier = string(in.String())
			}
		case "m":
			if in.IsNull() {
				in.Skip()
				out.Matches = nil
			} else {
				in.Delim('[')
				if out.Matches == nil {
					if !in.IsDelim(']') {
						out.Matches = make([]matchJSON, 0, 4)
					} else {
						out.Matches = []matchJSON{}
					}
				} else {
					out.Matches = (out.Matches)[:0]
				}
				for !in.IsDelim(']') {
					var v22 matchJSON
					easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm10(in, &v22)
					out.Matches = append(out.Matches, v22)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm7(out *jwriter.Writer, in patternJSON) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"i\":"
		out.RawString(prefix[1:])
		out.String(string(in.Identifier))
	}
	{
		const prefix string = ",\"m\":"
		out.RawString(prefix)
		if in.Matches == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v23, v24 := range in.Matches {
				if v23 > 0 {
					out.RawByte(',')
				}
				easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm10(out, v24)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}
func easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm10(in *jlexer.Lexer, out *matchJSON) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "o":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = uint64(in.Uint64())
			}
		case "l":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Length = uint64(in.Uint64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm10(out *jwriter.Writer, in matchJSON) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"o\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.Offset))
	}
	{
		const prefix string = ",\"l\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Length))
	}
	out.RawByte('}')
}
func easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm11(in *jlexer.Lexer, out *profilingInfoJSONList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(profilingInfoJSONList, 0, 1)
			} else {
				*out = profilingInfoJSONList{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v25 profilingInfoJSON
			easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm12(in, &v25)
			*out = append(*out, v25)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm11(out *jwriter.Writer, in profilingInfoJSONList) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v26, v27 := range in {
			if v26 > 0 {
				out.RawByte(',')
			}
			easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm12(out, v27)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v profilingInfoJSONList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v profilingInfoJSONList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *profilingInfoJSONList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *profilingInfoJSONList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm11(l, v)
}
func easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm12(in *jlexer.Lexer, out *profilingInfoJSON) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "n":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Namespace = string(in.String())
			}
		case "r":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Rule = string(in.String())
			}
		case "p":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PatternMatchingTime = float64(in.Float64())
			}
		case "c":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ConditionExecTime = float64(in.Float64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm12(out *jwriter.Writer, in profilingInfoJSON) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"n\":"
		out.RawString(prefix[1:])
		out.String(string(in.Namespace))
	}
	{
		const prefix string = ",\"r\":"
		out.RawString(prefix)
		out.String(string(in.Rule))
	}
	{
		const prefix string = ",\"p\":"
		out.RawString(prefix)
		out.Float64(float64(in.PatternMatchingTime))
	}
	{
		const prefix string = ",\"c\":"
		out.RawString(prefix)
		out.Float64(float64(in.ConditionExecTime))
	}
	out.RawByte('}')
}
func easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm13(in *jlexer.Lexer, out *compileErrorList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(compileErrorList, 0, 0)
			} else {
				*out = compileErrorList{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v28 CompileError
			easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm14(in, &v28)
			*out = append(*out, v28)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm13(out *jwriter.Writer, in compileErrorList) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v29, v30 := range in {
			if v29 > 0 {
				out.RawByte(',')
			}
			easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm14(out, v30)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v compileErrorList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm13(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v compileErrorList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm13(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *compileErrorList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm13(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *compileErrorList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm13(l, v)
}
func easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm14(in *jlexer.Lexer, out *CompileError) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = CompileErrorType(in.String())
			}
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = string(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "line":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Line = int(in.Int())
			}
		case "column":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Column = int(in.Int())
			}
		case "labels":
			if in.IsNull() {
				in.Skip()
				out.Labels = nil
			} else {
				in.Delim('[')
				if out.Labels == nil {
					if !in.IsDelim(']') {
						out.Labels = make([]Label, 0, 0)
					} else {
						out.Labels = []Label{}
					}
				} else {
					out.Labels = (out.Labels)[:0]
				}
				for !in.IsDelim(']') {
					var v31 Label
					easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm2(in, &v31)
					out.Labels = append(out.Labels, v31)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "footers":
			if in.IsNull() {
				in.Skip()
				out.Footers = nil
			} else {
				in.Delim('[')
				if out.Footers == nil {
					if !in.IsDelim(']') {
						out.Footers = make([]Footer, 0, 2)
					} else {
						out.Footers = []Footer{}
					}
				} else {
					out.Footers = (out.Footers)[:0]
				}
				for !in.IsDelim(']') {
					var v32 Footer
					easyjson6a975c40DecodeGithubComVirusTotalYaraXGoWasm3(in, &v32)
					out.Footers = append(out.Footers, v32)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm14(out *jwriter.Writer, in CompileError) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix)
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"line\":"
		out.RawString(prefix)
		out.Int(int(in.Line))
	}
	{
		const prefix string = ",\"column\":"
		out.RawString(prefix)
		out.Int(int(in.Column))
	}
	if len(in.Labels) != 0 {
		const prefix string = ",\"labels\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v33, v34 := range in.Labels {
				if v33 > 0 {
					out.RawByte(',')
				}
				easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm2(out, v34)
			}
			out.RawByte(']')
		}
	}
	if len(in.Footers) != 0 {
		const prefix string = ",\"footers\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v35, v36 := range in.Footers {
				if v35 > 0 {
					out.RawByte(',')
				}
				easyjson6a975c40EncodeGithubComVirusTotalYaraXGoWasm3(out, v36)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix)
		out.String(string(in.Text))
	}
	out.RawByte('}')
}
