name: ci
on:
  pull_request:
  push:
jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
          - msrv
          - stable
          - nightly
          - macos
          - win-msvc
        include:
          - build: msrv
            os: ubuntu-latest
            rust: 1.66.1
          - build: stable
            os: ubuntu-latest
            rust: stable
          - build: nightly
            os: ubuntu-latest
            rust: nightly
          - build: macos
            os: macos-latest
            rust: stable
          - build: win-msvc
            os: windows-latest
            rust: stable
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --all-targets
        env:
          RUSTFLAGS: -Awarnings # Allow all warnings
