name: Golang package

on:
  push:
    paths:
    - 'go/**'
    - '.github/workflows/golang.yaml'

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [ '1.26.x', '1.27.x' ]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: ${{ matrix.go-version }}

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # v1
      with:
        toolchain: stable

    - name: Install cargo-c
      run: cargo install cargo-c

    - name: Build and install Rust library
      run: cargo cinstall -p yara-x-capi --release --pkgconfigdir=${{ github.workspace }} --includedir=${{ github.workspace }} --libdir=${{ github.workspace }}

    - name: Run Go tests
      run: |
        cd go
        go test
      env:
        PKG_CONFIG_PATH: ${{ github.workspace }}
        LD_LIBRARY_PATH: ${{ github.workspace }}