name: Check PR title
on:
  pull_request_target:
    types:
    - opened
    - edited
    - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
    - uses: aslafy-z/conventional-pr-title-action@v3
      if: github.base_ref == 'master'
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}