name: Publish NPM package

on:
  create:
    tags:
      - 'v*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/

      - name: Install toml
        run: pip install toml

      - name: Install wasm-pack
        run: cargo install --locked wasm-pack

      - name: Install wasm-opt
        run: cargo install --locked wasm-opt

      - name: Install wasm-bindgen
        run: cargo install --locked wasm-bindgen-cli

      - name: Sync version
        run: python .github/scripts/sync_version.py

      - name: Build and publish package
        run: cd js-wasm && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}