name: Python extension

on:
  push:
    paths:
    - 'py/**'
    - '.github/workflows/python.yaml'

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9", "3.10", "3.11", "3.12", "3.13", "3.14" ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash --noprofile --norc -eEuo pipefail {0}
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Test Python
      run: |
        pip install virtualenv
        virtualenv venv; source venv/bin/activate
        python -m pip install --upgrade pip maturin>=1.7.8
        python -m pip install pytest
        maturin develop --manifest-path py/Cargo.toml --features=test_proto2-module,test_proto3-module
        pytest py
