name: Language server WebAssembly build
on:
  push:
    paths:
    - 'parser/**'
    - 'fmt/**'
    - 'ls/**'
    - '.github/workflows/wasm.yaml'
    tags-ignore:
    - '**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@2c7215f132e9ebf062739d9130488b56d53c060c # v1.97.1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      
      - name: Build LS
        run: cargo build --target wasm32-unknown-unknown --no-default-features -p yara-x-ls --lib --release